let g:isWin = has('win32')
let g:isWSL = system('uname -r') =~ ".*microsoft.*" ? 1 : 0
if g:isWin
    let $VIMDIR=expand("$HOME/vimfiles")
else
    let $VIMDIR=expand("$HOME/.vim")
endif
runtime! config/*.vim
