let g:isWin = has('win32')
if has('unix') && system('uname -r') =~ ".*microsoft.*"
    let g:isWSL=1
else
    let g:isWSL=0
endif
if g:isWin
    let $VIMDIR=expand("$HOME/vimfiles")
else
    let $VIMDIR=expand("$HOME/.vim")
endif
runtime! config/*.vim
