# aliases
alias :q="exit"
alias ran="ranger"
alias py="python3"
alias python="python3"
alias py3="python3"
alias pip="pip3"
alias tp="ping -c 3 google.com"
alias dock="docker"
alias dockc="docker-compose"

# git aliases
alias g="git"
alias gst="git status"
alias gl="git log --oneline"
alias gd="git diff"
alias ga="git add"
alias gcm="git commit -m"
alias rcm="git commit --amend"
alias gb="git branch"
alias gba="git branch -a"
alias gbd="git branch -d"
alias gs="git switch"
alias gsc="git switch -c"
alias gm="git merge"
alias gr="git restore"
alias reset="git reset"
alias push="git push"
alias opush="git push origin"
alias pull="git pull"
alias fetch="git fetch"
alias clone="git clone"
