# default
alias l="ls"
alias cl="clear"
alias tp="ping -c 3"
alias ..="cd .."
alias ..2="cd ../.."
alias ..3="cd ../../.."
alias configs="cd $HOME/Projects/github.com/IRcpjs/config"
alias windir="cd /mnt/c/Users/$USER"

# external tools
alias ran="ranger"
alias vi="vim"
alias v="vim ."
alias cm="rclone"
alias run="make run"

# python
alias python="python3"
alias py="python3"
alias pip="pip3"
alias act="pipenv shell"

# git
alias g="git"
alias gst="git status"
alias gl="git log --oneline"
alias gd="git diff"
alias gdc="git diff --cached"
alias ga="git add"
alias gc="git commit"
alias gcm="git commit -m"
alias rcm="git commit --amend"
alias gb="git branch"
alias gba="git branch -a"
alias gbd="git branch -d"
alias gs="git switch"
alias gsc="git switch -c"
alias gm="git merge"
alias reset="git reset"
alias push="git push"
alias opush="git push origin"
alias pull="git pull"
alias fetch="git fetch"
alias clone="git clone"
